final List<Map<String, dynamic>> products = [
  {
    "Title": "Parlour Chair",
    "Price": 399,
    "ImageUrl": "assets/images/3.png",
    "Rating": 1.0,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Bed",
    "Price": 789,
    "ImageUrl": "assets/images/b1.png",
    "Rating": 2.5,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Table",
    "Price": 140,
    "ImageUrl": "assets/images/t1.png",
    "Rating": 1.5,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Parlour Chair",
    "Price": 240,
    "ImageUrl": "assets/images/1.png",
    "Rating": 3.5,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Bed",
    "Price": 999,
    "ImageUrl": "assets/images/b2.png",
    "Rating": 3.0,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Parlour Chair",
    "Price": 299,
    "ImageUrl": "assets/images/2.png",
    "Rating": 5.0,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Bed",
    "Price": 909,
    "ImageUrl": "assets/images/b3.png",
    "Rating": 4.5,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },

  {
    "Title": "Table",
    "Price": 120,
    "ImageUrl": "assets/images/t2.png",
    "Rating": 3.5,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Bed",
    "Price": 889,
    "ImageUrl": "assets/images/b4.png",
    "Rating": 5.0,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Sofa",
    "Price": 267,
    "ImageUrl": "assets/images/s3.png",
    "Rating": 1.0,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Parlour Chair",
    "Price": 345,
    "ImageUrl": "assets/images/4.png",
    "Rating": 2.5,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Sofa",
    "Price": 376,
    "ImageUrl": "assets/images/s4.png",
    "Rating": 1.0,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Bed",
    "Price": 763,
    "ImageUrl": "assets/images/b5.png",
    "Rating": 5.0,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Sofa",
    "Price": 338,
    "ImageUrl": "assets/images/s5.png",
    "Rating": 5.0,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Parlour Chair",
    "Price": 787,
    "ImageUrl": "assets/images/5.png",
    "Rating": 3.0,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Table",
    "Price": 444,
    "ImageUrl": "assets/images/t4.png",
    "Rating": 4.5,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Parlour Chair",
    "Price": 423,
    "ImageUrl": "assets/images/6.png",
    "Rating": 4.5,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Sofa",
    "Price": 999,
    "ImageUrl": "assets/images/s6.png",
    "Rating": 3.5,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Table",
    "Price": 280,
    "ImageUrl": "assets/images/t3.png",
    "Rating": 3.5,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Parlour Chair",
    "Price": 898,
    "ImageUrl": "assets/images/7.png",
    "Rating": 1.5,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Sofa",
    "Price": 162,
    "ImageUrl": "assets/images/s7.png",
    "Rating": 4.0,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
  {
    "Title": "Table",
    "Price": 699,
    "ImageUrl": "assets/images/t5.png",
    "Rating": 5.0,
    "Colors": ["Ash", "White", "Black", "Blue", "Yellow"],
  },
];
